<a href="https://colab.research.google.com/github/07Akshaya/Statistical-Learning-e22019/blob/main/Assignment_4_e22019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas numpy plotly scipy scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from plotly.subplots import make_subplots

from sklearn.preprocessing import (
    MinMaxScaler,
    StandardScaler,
    RobustScaler,
    OrdinalEncoder
)

from scipy.stats import chi2_contingency

In [ ]:
class PlottingMethods:

    def plot_bar_chart(self, data, title="Bar Chart"):
        return data.plot(kind='bar', title=title)

    def plot_pie_chart(self, data, title="Pie Chart"):
        return data.plot(kind='pie', autopct='%1.1f%%', title=title)

    def plot_histogram(self, data, title="Histogram"):
        return data.plot(kind='hist', bins=20, title=title)

    def display_image(self, img_path):
        from IPython.display import Image, display
        display(Image(filename=img_path))

In [ ]:
class DataInspector:

    def __init__(self):
        self.df = None
        self.plotter = PlottingMethods()

    def upload_data(self, file_path=None):
        if file_path:
            self.df = pd.read_csv(file_path)
        print("Data loaded")
        return self.df

    def get_summary(self):
        print("Shape:", self.df.shape)
        display(self.df.head(20))

    def column_details(self):
        return pd.DataFrame({
            "Column": self.df.columns,
            "Type": self.df.dtypes
        })

    def show_missing_data(self):
        return self.df.isnull().sum()

    def handle_missing_values(self, strategy="mean", constant=None):

        for col in self.df.columns:

            if self.df[col].isnull().sum() > 0:

                if self.df[col].dtype in [np.float64, np.int64]:

                    if strategy == "mean":
                        self.df[col].fillna(self.df[col].mean(), inplace=True)

                    elif strategy == "median":
                        self.df[col].fillna(self.df[col].median(), inplace=True)

                    elif strategy == "constant":
                        self.df[col].fillna(constant, inplace=True)

                    elif strategy == "mode":
                        self.df[col].fillna(self.df[col].mode()[0], inplace=True)

    def remove_duplicates(self):
        self.df = self.df.drop_duplicates()

    def handle_outliers(self, columns, find_and_delete=True):

        for col in columns:

            Q1 = self.df[col].quantile(0.25)
            Q3 = self.df[col].quantile(0.75)
            IQR = Q3 - Q1

            lower = Q1 - 1.5 * IQR
            upper = Q3 + 1.5 * IQR

            if find_and_delete:
                self.df = self.df[(self.df[col] >= lower) & (self.df[col] <= upper)]

    def delete_columns(self, cols):
        self.df.drop(columns=cols, inplace=True, errors='ignore')

    def delete_rows(self, rows):
        self.df.drop(index=rows, inplace=True, errors='ignore')

    def extract_normalized_numeric_data(self, method="minmax"):

        num = self.df.select_dtypes(include=np.number)

        if method == "minmax":
            return (num - num.min()) / (num.max() - num.min())

        elif method == "standard":
            return (num - num.mean()) / num.std()

        elif method == "robust":
            return (num - num.median()) / (num.quantile(0.75) - num.quantile(0.25))

    def extract_normalized_categorical_data(self, method="onehot"):

        cat = self.df.select_dtypes(exclude=np.number)

        if method == "onehot":
            return pd.get_dummies(cat)

        elif method == "ordinal":
            return cat.apply(lambda x: pd.factorize(x)[0])

        elif method == "uniform":
            return cat.apply(lambda x: pd.factorize(x)[0] / len(x))

    def create_normalized_data_df(self):

        num = self.extract_normalized_numeric_data()
        cat = self.extract_normalized_categorical_data()

        return pd.concat([num, cat], axis=1)

In [ ]:
def handle_missing_values(self, strategy="mean", constant=None):

    for col in self.df.columns:

        if self.df[col].isnull().sum() > 0:

            if self.df[col].dtype in [np.float64, np.int64]:

                if strategy == "mean":
                    self.df[col].fillna(self.df[col].mean(), inplace=True)

                elif strategy == "median":
                    self.df[col].fillna(self.df[col].median(), inplace=True)

                elif strategy == "constant":
                    self.df[col].fillna(constant, inplace=True)

                elif strategy == "mode":
                    self.df[col].fillna(self.df[col].mode()[0], inplace=True)

In [ ]:
def remove_duplicates(self):
    self.df = self.df.drop_duplicates()

In [ ]:
def handle_outliers(self, columns, find_and_delete=True):

    for col in columns:

        Q1 = self.df[col].quantile(0.25)
        Q3 = self.df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        if find_and_delete:
            self.df = self.df[(self.df[col] >= lower) & (self.df[col] <= upper)]

In [ ]:
def delete_columns(self, cols):
    self.df.drop(columns=cols, inplace=True, errors='ignore')

def delete_rows(self, rows):
    self.df.drop(index=rows, inplace=True, errors='ignore')

In [ ]:
def extract_normalized_numeric_data(self, method="minmax"):

    num = self.df.select_dtypes(include=np.number)

    if method == "minmax":
        return (num - num.min()) / (num.max() - num.min())

    elif method == "standard":
        return (num - num.mean()) / num.std()

    elif method == "robust":
        return (num - num.median()) / (num.quantile(0.75) - num.quantile(0.25))

In [ ]:
def extract_normalized_categorical_data(self, method="onehot"):

    cat = self.df.select_dtypes(exclude=np.number)

    if method == "onehot":
        return pd.get_dummies(cat)

    elif method == "ordinal":
        return cat.apply(lambda x: pd.factorize(x)[0])

    elif method == "uniform":
        return cat.apply(lambda x: pd.factorize(x)[0] / len(x))

In [ ]:
def create_normalized_data_df(self):

    num = self.extract_normalized_numeric_data()
    cat = self.extract_normalized_categorical_data()

    return pd.concat([num, cat], axis=1)

In [ ]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
inspector = DataInspector()
inspector.df = pd.read_csv(url)

inspector.df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
inspector.get_summary()

inspector.show_missing_data()

inspector.handle_missing_values(strategy='median')

inspector.remove_duplicates()

inspector.handle_outliers(columns=['Age','Fare'], find_and_delete=True)

numeric = inspector.extract_normalized_numeric_data(method='robust')

categorical = inspector.extract_normalized_categorical_data(method='onehot')

final_df = inspector.create_normalized_data_df()

final_df.head()

Shape: (718, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbing, Mr. Anthony","Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)",...,Cabin_F G63,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_G6,Cabin_T,Embarked_C,Embarked_Q,Embarked_S
0,0.000000,0.0,1.0,0.372093,0.2,0.000000,0.153928,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,0.002247,1.0,1.0,0.465116,0.0,0.000000,0.168259,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,0.004494,0.0,1.0,0.674419,0.0,0.000000,0.170913,False,False,False,...,False,False,False,False,False,False,False,False,False,True
5,0.005618,0.0,1.0,0.511628,0.0,0.000000,0.179582,False,False,False,...,False,False,False,False,False,False,False,False,True,False
8,0.008989,1.0,1.0,0.488372,0.0,0.333333,0.236376,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
# Re-instantiate DataInspector to ensure the latest class definition is used
inspector = DataInspector()
inspector.df = pd.read_csv(url) # Reload data into the new inspector instance

inspector.get_summary()

inspector.show_missing_data()

inspector.handle_missing_values(strategy='median')

inspector.remove_duplicates()

inspector.handle_outliers(columns=['Age','Fare'], find_and_delete=True)

numeric = inspector.extract_normalized_numeric_data(method='robust')

categorical = inspector.extract_normalized_categorical_data(method='onehot')

final_df = inspector.create_normalized_data_df()

final_df.head()

Shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

/tmp/ipykernel_3036/1163428466.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].median(), inplace=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbing, Mr. Anthony","Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)",...,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Embarked_C,Embarked_Q,Embarked_S
0,0.000000,0.0,1.0,0.372549,0.2,0.0,0.118118,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,0.002247,1.0,1.0,0.450980,0.0,0.0,0.129115,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,0.003371,1.0,0.0,0.627451,0.2,0.0,0.865114,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,0.004494,0.0,1.0,0.627451,0.0,0.0,0.131152,False,False,False,...,False,False,False,False,False,False,False,False,False,True
5,0.005618,0.0,1.0,0.490196,0.0,0.0,0.137804,False,False,False,...,False,False,False,False,False,False,False,False,True,False